### ISSUE TITLE
Exercise 3: Error when running and verifying

### ISSUE THREAD

**Issue by andrewn** [CardboardIoT/smart-pinhole-workshop#2]
This isn't the right solution, but I don't get any helpful errors telling me which bit is wrong.

Program:

``` js
var mqtt = require('mqtt');
var client  = mqtt.connect({
  host: 'test.mosquitto.org',
  port: 1883
});

var five = require('johnny-five')

client.on('connect', function () {
  var board = new five.Board();
  board.on('ready', function () {
     var sensor = five.Sensor('A0');
     sensor.scale(0, 1).on("change", function() {
      client.publish("ciot/pinhole/light/value", this.value.toString(), { retain: true });
    });
  });
});
```

Output:

```
~/Projects/cardboardiot/smart-pinhole-course » smart-pinhole-workshop verify answers/03-let-there-be-light.js 
1445684876606 Device(s) /dev/cu.usbserial-FAKEID  
1445684876649 Connected /dev/cu.usbserial-FAKEID  
1445684877059 Repl Initialized  
>> /Users/andrew/Projects/cardboardiot/smart-pinhole-workshop/node_modules/sinon/lib/sinon/spy.js:193
                    throw exception;
                          ^
InvalidResetException: Cannot reset Sinon function while invoking it. Move the call to .reset outside of the callback.
    at Function.spyApi.reset (/Users/andrew/Projects/cardboardiot/smart-pinhole-workshop/node_modules/sinon/lib/sinon/spy.js:94:31)
    at Function.create (/Users/andrew/Projects/cardboardiot/smart-pinhole-workshop/node_modules/sinon/lib/sinon/spy.js:144:23)
    at Object.spy (/Users/andrew/Projects/cardboardiot/smart-pinhole-workshop/node_modules/sinon/lib/sinon/spy.js:26:28)
    at Object.SpyConstructor (/Users/andrew/Projects/cardboardiot/smart-pinhole-workshop/stubs/five.js:26:27)
    at Function.invoke (/Users/andrew/Projects/cardboardiot/smart-pinhole-workshop/node_modules/sinon/lib/sinon/spy.js:172:59)
    at Object.proxy [as Sensor] (eval at createProxy (/Users/andrew/Projects/cardboardiot/smart-pinhole-workshop/node_modules/sinon/lib/sinon/spy.js:77:86), <anonymous>:1:35)
    at Board.<anonymous> (/Users/andrew/Projects/cardboardiot/smart-pinhole-course/answers/03-let-there-be-light.js:12:24)
    at Board.emit (events.js:104:17)
    at process._tickDomainCallback (node.js:381:11)
```

**Comment by ezodude** [comment]
The culprit is this line:

```
var sensor = five.Sensor('A0');
```

This is a Sinon constructor. It's not being called with `new Sensor...`. So Sinon freaks.

I have to ponder that one. No immediate solution.

**Comment by andrewn** [comment]
Programmer error on my part then. That's fine -- the Sensor API docs all use `new` so I should have too.
